# Generated by Django 6.0.6 on 2026-06-26 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('PROFESSOR', 'Professor'), ('ALUNO', 'Aluno')], max_length=20)),
                ('usado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AreaConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Gerado automaticamente (ex: LOG2026001)', max_length=20, unique=True, verbose_name='Código da Disciplina')),
                ('nome', models.CharField(max_length=200, verbose_name='Disciplina')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas', to='academico.areaconhecimento', verbose_name='Área do Conhecimento')),
                ('professor', models.ForeignKey(limit_choices_to={'tipo_usuario': 'PROFESSOR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Professor Responsável')),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Aula')),
                ('conteudo', models.TextField(verbose_name='Conteúdo da Aula')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem da Aula')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='academico.disciplina', verbose_name='Disciplina')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('disciplina', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Instituição')),
                ('professor', models.ForeignKey(limit_choices_to={'tipo_usuario': 'PROFESSOR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Professor Responsável')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VIDEO', 'Vídeo'), ('PDF', 'PDF'), ('LINK', 'Link')], max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='aulas/materiais/')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='academico.aula')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Turma')),
                ('ano', models.PositiveIntegerField(default=2026)),
                ('codigo_convite', models.CharField(blank=True, editable=False, max_length=3, unique=True)),
                ('disciplinas', models.ManyToManyField(blank=True, related_name='turmas', to='academico.disciplina', verbose_name='Disciplinas vinculadas')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='academico.instituicao', verbose_name='Instituição')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='academico.turma')),
            ],
        ),
    ]
