# Generated by Django 6.0.6 on 2026-06-26 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_delete_recurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='academico.aula')),
            ],
        ),
    ]
