# Generated by Django 6.0.6 on 2026-06-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(help_text='Cole o link do YouTube aqui'),
        ),
    ]
