# Generated by Django 6.0.6 on 2026-06-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_disciplina_professor_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(blank=True, help_text='Gerado automaticamente (ex: LOG2026001)', max_length=20, unique=True, verbose_name='Código da Disciplina'),
        ),
    ]
