# Generated by Django 6.0.6 on 2026-06-25 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_disciplina_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Turma')),
                ('ano', models.PositiveIntegerField(default=2026)),
                ('disciplinas', models.ManyToManyField(blank=True, related_name='turmas', to='academico.disciplina', verbose_name='Disciplinas vinculadas')),
                ('professor', models.ForeignKey(limit_choices_to={'tipo_usuario': 'PROFESSOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='turmas_gerenciadas', to=settings.AUTH_USER_MODEL, verbose_name='Professor Responsável')),
            ],
        ),
    ]
