# Generated by Django 6.0.6 on 2026-06-27 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_video_thumbnail_url_alter_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('link', models.URLField(help_text='Cole o link do PDF hospedado (Google Drive, Dropbox, etc.)')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='academico.aula')),
            ],
        ),
    ]
