# Generated by Django 6.0.6 on 2026-06-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_remove_turma_professor_instituicao_turma_instituicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('PROFESSOR', 'Professor'), ('ALUNO', 'Aluno')], max_length=20)),
                ('usado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterUniqueTogether(
            name='aula',
            unique_together={('disciplina', 'ordem')},
        ),
    ]
