# Generated by Django 6.0.6 on 2026-06-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_linkutil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='turma',
        ),
        migrations.AddField(
            model_name='aluno',
            name='turmas',
            field=models.ManyToManyField(blank=True, related_name='alunos', to='academico.turma'),
        ),
    ]
