# Generated by Django 6.0.6 on 2026-06-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='tutoriais/'),
        ),
    ]
