# Generated by Django 6.0.6 on 2026-06-25 21:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_turma_codigo_convite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='codigo_convite',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
