# Generated by Django 6.0.6 on 2026-06-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_tutorial_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='imagem_url',
            field=models.URLField(blank=True, help_text='Ou cole a URL da imagem aqui', null=True),
        ),
    ]
