# Generated by Django 6.0.6 on 2026-06-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_alter_turma_codigo_convite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='codigo_convite',
            field=models.CharField(blank=True, editable=False, max_length=3),
        ),
    ]
