# Generated by Django 6.0.6 on 2026-06-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0012_tutorial_imagem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='turmas',
            field=models.ManyToManyField(blank=True, related_name='alunos_vinculados', to='academico.turma'),
        ),
    ]
