# Generated by Django 6.0.6 on 2026-06-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0013_alter_turma_codigo_convite'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
    ]
