# Generated by Django 6.0.6 on 2026-06-26 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0014_aula_publicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VIDEO', 'Vídeo'), ('PDF', 'PDF'), ('LINK', 'Link')], max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='aulas/materiais/')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='academico.aula')),
            ],
        ),
    ]
