# Generated by Django 6.0.6 on 2026-06-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0015_alter_aluno_turmas_alter_aluno_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='turmas',
            field=models.ManyToManyField(blank=True, related_name='alunos_na_turma', to='academico.turma'),
        ),
    ]
