# Generated by Django 6.0.6 on 2026-06-30 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0016_alter_aluno_turmas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Informativo'), ('ALTA', 'Urgente')], default='BAIXA', max_length=10)),
                ('fixado', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='academico.turma')),
            ],
            options={
                'ordering': ['-fixado', '-data_criacao'],
            },
        ),
    ]
