# Generated by Django 6.0.6 on 2026-07-21 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0018_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioContextual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_ancora', models.CharField(help_text='Identificador ou termo do texto onde esta nota se aplica', max_length=50)),
                ('texto', models.TextField(verbose_name='Comentário do Professor')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_contextuais', to='academico.aula', verbose_name='Aula')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Comentário Contextual',
                'verbose_name_plural': 'Comentários Contextuais',
                'ordering': ['data_criacao'],
            },
        ),
    ]
