# Generated by Django 6.0.6 on 2026-07-22 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0019_comentariocontextual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='imagem_url',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, related_name='tutoriais', to='academico.disciplina'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tutoriais_criados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='turmas',
            field=models.ManyToManyField(blank=True, related_name='tutoriais', to='academico.turma'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='conteudo',
            field=models.TextField(help_text='Suporta Markdown ou HTML'),
        ),
    ]
