# Generated by Django 6.0.6 on 2026-07-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0020_remove_tutorial_descricao_remove_tutorial_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='tutoriais/'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='imagem_url',
            field=models.URLField(blank=True, help_text='Ou cole o link de uma imagem externa', max_length=500, null=True),
        ),
    ]
