# Generated by Django 6.0.6 on 2026-07-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0021_tutorial_imagem_tutorial_imagem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
