# Generated by Django 6.0.6 on 2026-07-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0022_alter_tutorial_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='disciplinas',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='turmas',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição curta do tutorial', null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='conteudo',
            field=models.TextField(blank=True, help_text='Conteúdo em Markdown', null=True),
        ),
    ]
