# Generated by Django 6.0.6 on 2026-07-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0023_remove_tutorial_disciplinas_remove_tutorial_turmas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='turmas',
            field=models.ManyToManyField(blank=True, related_name='tutoriais', to='academico.turma', verbose_name='Turmas com acesso'),
        ),
    ]
