# Generated by Django 6.0.6 on 2026-06-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor')], default='ALUNO', max_length=10, verbose_name='Tipo de Usuário'),
        ),
    ]
