# Generated by Django 6.0.6 on 2026-06-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('PROFESSOR', 'Professor'), ('ALUNO', 'Aluno')], default='ALUNO', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
